package works.tonny.apps.user.model;

// Generated 2012-12-3 13:14:27 by Hibernate Tools /Coder tools 1.0.0 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Job generated by hbm2java
 * 
 * @author Tonny Liu
 */
@Entity
@Table(name = "u_job")
public class Job implements java.io.Serializable {
	/**
	 * @Fields serialVersionUID :
	 */
	private static final long serialVersionUID = 1L;

	private String id;
	private String name;
	private String info;
	private Integer orderNo;
	private Set<JobLevel> jobLevels = new HashSet<JobLevel>(0);

	public Job() {
	}

	public Job(String id, String name) {
		setId(id);
		setName(name);
	}

	public Job(String id, String name, String info, Integer orderNo, Set<JobLevel> jobLevels) {
		setId(id);
		setName(name);
		setInfo(info);
		setOrderNo(orderNo);
		setJobLevels(jobLevels);
	}

	@Id
	@GeneratedValue(generator = "idGenerator")
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@Column(length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(length = 500)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "order_no")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	@OneToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.EAGER, mappedBy = "job")
	// @JoinTable(name = "u_job_level", joinColumns = @JoinColumn(name = "job_id"))
	@OrderBy("level desc")
	public Set<JobLevel> getJobLevels() {
		return this.jobLevels;
	}

	public void setJobLevels(Set<JobLevel> jobLevels) {
		this.jobLevels = jobLevels;
	}

}
