package works.tonny.apps.user.model;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.GenericGenerator;

// Generated 2012-12-3 13:14:27 by Hibernate Tools /Coder tools 1.0.0 3.4.0.CR1

/**
 * UserPrivilege 职位权限配置 generated by hbm2java
 * 
 * @author Tonny Liu
 */
@Embeddable
@Entity
@Table(name = "a_position_privilege")
public class PositionPrivilege extends EntityPrivilege {
	private Position position;

	public PositionPrivilege() {
		super();
	}

	/**
	 * @see com.zxtx.apps.user.EntityPrivilege#getEntity()
	 */
	@Override
	@Transient
	public Object getEntity() {
		return position;
	}

	@ManyToOne()
	@JoinColumn(name = "position_id")
	public Position getPosition() {
		return position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

}
