package works.tonny.apps.user.model;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import works.tonny.apps.user.Privilege;
import works.tonny.apps.user.Role;

// Generated 2012-12-3 13:14:27 by Hibernate Tools /Coder tools 1.0.0 3.4.0.CR1

/**
 * UserPrivilege 角色权限配置 generated by hbm2java
 * 
 * @author Tonny Liu
 */
@Embeddable
@Entity
@Table(name = "a_role_privilege")
public class RolePrivilege extends EntityPrivilege {
	private Role role;

	public RolePrivilege() {
		super();
	}

	/**
	 * @param role2
	 * @param privilege2
	 */
	public RolePrivilege(Role role, Privilege privilege) {
		this.role = role;
		this.privilege = privilege;
	}

	/**
	 * @see com.zxtx.apps.user.EntityPrivilege#getEntity()
	 */
	@Override
	@Transient
	public Object getEntity() {
		return role;
	}

	@ManyToOne()
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
