package works.tonny.apps.user.model;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;

import works.tonny.apps.user.Privilege;
import works.tonny.apps.user.User;

// Generated 2012-12-3 13:14:27 by Hibernate Tools /Coder tools 1.0.0 3.4.0.CR1

/**
 * UserPrivilege 用户权限配置 generated by hbm2java
 * 
 * @author Tonny Liu
 */
@Embeddable
@Entity
@Table(name = "a_user_privilege")
public class UserPrivilege extends EntityPrivilege {
	private User user;

	public UserPrivilege() {
		super();
	}

	public UserPrivilege(User user, Privilege privilege) {
		super();
		this.privilege = privilege;
		this.user = user;
	}

	@ManyToOne(cascade = CascadeType.DETACH)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @see com.zxtx.apps.user.EntityPrivilege#getEntity()
	 */
	@Override
	@Transient
	public Object getEntity() {
		return user;
	}
}
