package works.tonny.apps.user.model;

import works.tonny.apps.user.User;

import javax.persistence.*;
import java.util.Set;

// Generated 2012-12-3 13:14:27 by Hibernate Tools /Coder tools 1.0.0 3.4.0.CR1

/**
 * UserInfo generated by hbm2java
 *
 * @author Tonny Liu
 */
@Entity()
@Table(name = "u_user_info")
@Inheritance(strategy = InheritanceType.JOINED)
@PrimaryKeyJoinColumn(name = "user_id")
public class UserInfo extends User {
    /**
     * @Fields serialVersionUID :
     */
    public static final long serialVersionUID = 1L;
    private transient Position position;
    private transient Title title;

    private transient Set<Position> positions;

    public UserInfo() {

    }

    @ManyToOne
    @JoinColumn(name = "position_id")
    public Position getPosition() {
        return this.position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    @ManyToOne
    @JoinColumn(name = "title_id")
    public Title getTitle() {
        return this.title;
    }

    public void setTitle(Title title) {
        this.title = title;
    }

    @ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(name = "u_user_position", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "position_id"))
    public Set<Position> getPositions() {
        return positions;
    }

    public void setPositions(Set<Position> positions) {
        this.positions = positions;
    }

    /**
     * @see com.zxtx.apps.user.User#toString()
     */
    @Override
    public String toString() {
        return super.toString();
    }

}
