package works.tonny.apps.core;

// Generated 2012-7-17 9:34:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import works.tonny.apps.Entity;

/**
 * Element generated by hbm2java
 * 
 * @author Tonny Liu
 */
@javax.persistence.Entity
@Table(name = "fr_element")
public class Element extends Entity {
	/**
	 * @Fields serialVersionUID :
	 */
	private static final long serialVersionUID = 1L;

	private String name;
	private String dataType;
	private String viewType;
	private String options;
	private String defaultValue;
	private int required;
	private int minLength;
	private int maxLength;
	private String regex;
	private String catelog;
	private Date updateTime;
	private String admin;

	public Element() {
	}

	public Element(String id, String name, String dataType) {
		setId(id);
		setName(name);
		setDataType(dataType);
	}

	public Element(String id, String name, String dataType, String viewType, String options, String defaultValue,
					int required, int minLength, int maxLength, String regex, String catelog, Date updateTime,
					String admin) {
		setId(id);
		setName(name);
		setDataType(dataType);
		setViewType(viewType);
		setOptions(options);
		setDefaultValue(defaultValue);
		setRequired(required);
		setMinLength(minLength);
		setMaxLength(maxLength);
		setRegex(regex);
		setCatelog(catelog);
		setUpdateTime(updateTime);
		setAdmin(admin);
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see works.tonny.apps.Entity#getId()
	 */
	@Override
	@Id
	@GeneratedValue(generator = "idGenerator")
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@Column(length = 50)
	public String getId() {
		return super.getId();
	}

	@Column(length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(length = 20, name = "data_type")
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(length = 20, name = "view_type")
	public String getViewType() {
		return this.viewType;
	}

	public void setViewType(String viewType) {
		this.viewType = viewType;
	}

	@Column(length = 2000)
	public String getOptions() {
		return this.options;
	}

	public void setOptions(String options) {
		this.options = options;
	}

	@Column(length = 2000, name = "default_value")
	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public int getRequired() {
		return this.required;
	}

	public void setRequired(int required) {
		this.required = required;
	}

	@Column(name = "min_length")
	public int getMinLength() {
		return this.minLength;
	}

	public void setMinLength(int minLength) {
		this.minLength = minLength;
	}

	@Column(name = "max_length")
	public int getMaxLength() {
		return this.maxLength;
	}

	public void setMaxLength(int maxLength) {
		this.maxLength = maxLength;
	}

	@Column(length = 100)
	public String getRegex() {
		return this.regex;
	}

	public void setRegex(String regex) {
		this.regex = regex;
	}

	@Column(length = 50)
	public String getCatelog() {
		return this.catelog;
	}

	public void setCatelog(String catelog) {
		this.catelog = catelog;
	}

	@Column(name = "update_time")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(length = 50)
	public String getAdmin() {
		return this.admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

}
