package works.tonny.apps.core;

// Generated 2012-7-17 11:29:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import works.tonny.apps.Entity;

/**
 * FormElement generated by hbm2java
 * 
 * @author Tonny Liu
 */
@javax.persistence.Entity
@Table(name = "fr_form_element")
public class FormElement extends Entity {
	/**
	 * @Fields serialVersionUID :
	 */
	private static final long serialVersionUID = 1L;

	private Form form;
	private Element element;
	private String name;
	private String foreignForm;
	private String foreignKey;
	private Integer list;
	private Integer search;
	private Integer orderNo;
	private Date updateTime;
	private String admin;

	public FormElement() {
	}

	public FormElement(String id, Form form, Element element) {
		setId(id);
		setForm(form);
		setElement(element);
	}

	public FormElement(String id, Form form, Element element, String name, String foreignForm, String foreignKey,
						Integer list, Integer search, Integer orderNo, Date updateTime, String admin) {
		setId(id);
		setForm(form);
		setElement(element);
		setName(name);
		setForeignForm(foreignForm);
		setForeignKey(foreignKey);
		setList(list);
		setSearch(search);
		setOrderNo(orderNo);
		setUpdateTime(updateTime);
		setAdmin(admin);
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see works.tonny.apps.Entity#getId()
	 */
	@Override
	@Id
	@GeneratedValue(generator = "idGenerator")
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@Column(length = 50)
	public String getId() {
		return super.getId();
	}

	@ManyToOne
	@JoinColumn(name = "form_id")
	public Form getForm() {
		return this.form;
	}

	public void setForm(Form form) {
		this.form = form;
	}

	@ManyToOne
	@JoinColumn(name = "element_id")
	public Element getElement() {
		return this.element;
	}

	public void setElement(Element element) {
		this.element = element;
	}

	@Column(length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(length = 50, name = "foreign_form")
	public String getForeignForm() {
		return this.foreignForm;
	}

	public void setForeignForm(String foreignForm) {
		this.foreignForm = foreignForm;
	}

	@Column(length = 50, name = "foreign_key")
	public String getForeignKey() {
		return this.foreignKey;
	}

	public void setForeignKey(String foreignKey) {
		this.foreignKey = foreignKey;
	}

	public Integer getList() {
		return this.list;
	}

	public void setList(Integer list) {
		this.list = list;
	}

	public Integer getSearch() {
		return this.search;
	}

	public void setSearch(Integer search) {
		this.search = search;
	}

	@Column(name = "order_no")
	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "update_time")
	@Temporal(TemporalType.TIMESTAMP)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(length = 50)
	public String getAdmin() {
		return this.admin;
	}

	public void setAdmin(String admin) {
		this.admin = admin;
	}

}
