package works.tonny.apps.core;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import works.tonny.apps.Entity;

// Generated 2012-7-17 11:29:00 by Hibernate Tools 3.4.0.CR1

/**
 * FormValue generated by hbm2java
 * 
 * @author Tonny Liu
 */
@javax.persistence.Entity
@Table(name = "fr_form_value")
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class FormValue extends Entity {
	/**
	 * @Fields serialVersionUID :
	 */
	private static final long serialVersionUID = 1L;

	private FormElement formElement;
	private String itemId;

	public FormValue() {
	}

	public FormValue(String id, FormElement formElement, String itemId) {
		setId(id);
		setFormElement(formElement);
		setItemId(itemId);
	}

	/**
	 * {@inheritDoc}
	 * 
	 * @see works.tonny.apps.Entity#getId()
	 */
	@Id
	@GeneratedValue(generator = "idGenerator")
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@Column(length = 50)
	public String getId() {
		return super.getId();
	}

	@ManyToOne
	@JoinColumn(name = "element_id")
	public FormElement getFormElement() {
		return this.formElement;
	}

	public void setFormElement(FormElement formElement) {
		this.formElement = formElement;
	}

	@Column(name = "item_id", length = 50)
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Transient
	public abstract String getValue();

	public abstract void setValue(String value);
}
